sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: true
language: node_js
node_js:
  - lts/*
  - '10'
  - '12'
  - '14'

stages:
  - test
  - coverage
  # - docs

before_script:
  - npm prune

script: echo "Running tests with $(node -v) ..."

jobs:
  include:
    - stage: coverage
      script: npm run coverage
      name: 'Testing Coverage Report'