sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: true
language: node_js
node_js:
  - lts/*
  - '10'
  - '12'
  - '14'

stages:
  - lint
  - audit
  - test
  - coverage
  - docs

before_script:
  - npm prune

script:
  - echo "Running tests with $(node -v) ..."
  - npm run test

jobs:
  include:
    - stage: audit
      name: 'Security Audit'
      script:
        - npm audit
    - stage: lint
      name: 'Lint'
      script:
        - npm run lint
    - stage: coverage
      name: 'Testing Coverage Report'
      script: npm run coverage
    - stage: docs
      name: 'Code Documentation'
      script:
        - npm run docs
        - npm run docs:publish
